
name: CI_14_08_2026
on:
  push:
    branches:
        - main

  # workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: azure/login@v3
      - name: AZ login
        
        run: az login --service-principal -u "ec5cdf78-6172-4760-acb9-a9748a2d44cd" -p "SEW8Q~to1tD_utTeoOU-eQ7Uwk~AB-9TIUyOIb9i" --tenant "c04247ef-3725-47f1-93c2-18778afc86e8"

      - name: init
        run: terraform init          
    

