name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Terraform_Plan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
      
          
      - uses: azure/login@v3
        with:
          creds: |
            {
            "clientId": "ec5cdf78-6172-4760-acb9-a9748a2d44cd",
            "clientSecret": "SEW8Q~to1tD_utTeoOU-eQ7Uwk~AB-9TIUyOIb9i",
            "subscriptionId": "5f2215aa-254d-4cd3-ab18-8cdd7a251f56",
            "tenantId": "c04247ef-3725-47f1-93c2-18778afc86e8"
            }

      - name: Init
        run: terraform init  
        
      - name: plan
        run: terraform plan 
      - name: validate
        run: terraform validate              
    

