name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Terraform_Plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "5.2.0"
      
          
      - uses: azure/login@v3
        with:
          creds: |
            {
            "clientId": "c640f30d-cbee-490a-84c2-6f2bfa40c3c9",
            "clientSecret": "Pxl8Q~Cctdld8MOk~eFmEYuotEoDNMmswBWZua2-",
            "subscriptionId": "0e2f2b6f-1f5f-4582-8c39-1dcfd3fd1f88",
            "tenantId": "3c7bd315-a86f-4b23-90b9-6318c8a94eea"
            }

      - name: Init
        run: terraform init  
        
      - name: plan
        run: terraform plan        
    

